/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : CategoryId,
  'icon' : string,
  'name' : string,
  'color' : string,
}
export type CategoryId = bigint;
export interface Product {
  'id' : ProductId,
  'amazonUrl' : string,
  'title' : string,
  'featured' : boolean,
  'originalPrice' : bigint,
  'createdAt' : bigint,
  'recommended' : boolean,
  'description' : string,
  'imageUrl' : string,
  'category' : CategoryId,
  'rating' : number,
  'price' : bigint,
  'reviewCount' : bigint,
}
export type ProductId = bigint;
export interface SiteSettings {
  'heroImageUrl' : string,
  'heroSubtitle' : string,
  'siteName' : string,
  'heroTitle' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[Category], CategoryId>,
  'createProduct' : ActorMethod<[Product], ProductId>,
  'deleteCategory' : ActorMethod<[CategoryId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryById' : ActorMethod<[CategoryId], Category>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getProductById' : ActorMethod<[ProductId], Product>,
  'getProductsByCategory' : ActorMethod<[CategoryId], Array<Product>>,
  'getRecommendedProducts' : ActorMethod<[], Array<Product>>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'updateCategory' : ActorMethod<[Category], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateSiteSettings' : ActorMethod<[SiteSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];