/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CategoryId = IDL.Nat;
export const Category = IDL.Record({
  'id' : CategoryId,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
});
export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'amazonUrl' : IDL.Text,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'originalPrice' : IDL.Nat,
  'createdAt' : IDL.Int,
  'recommended' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : CategoryId,
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SiteSettings = IDL.Record({
  'heroImageUrl' : IDL.Text,
  'heroSubtitle' : IDL.Text,
  'siteName' : IDL.Text,
  'heroTitle' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([Category], [CategoryId], []),
  'createProduct' : IDL.Func([Product], [ProductId], []),
  'deleteCategory' : IDL.Func([CategoryId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryById' : IDL.Func([CategoryId], [Category], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductById' : IDL.Func([ProductId], [Product], ['query']),
  'getProductsByCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getRecommendedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedSampleData' : IDL.Func([], [], []),
  'updateCategory' : IDL.Func([Category], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CategoryId = IDL.Nat;
  const Category = IDL.Record({
    'id' : CategoryId,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
  });
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'amazonUrl' : IDL.Text,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'originalPrice' : IDL.Nat,
    'createdAt' : IDL.Int,
    'recommended' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : CategoryId,
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SiteSettings = IDL.Record({
    'heroImageUrl' : IDL.Text,
    'heroSubtitle' : IDL.Text,
    'siteName' : IDL.Text,
    'heroTitle' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([Category], [CategoryId], []),
    'createProduct' : IDL.Func([Product], [ProductId], []),
    'deleteCategory' : IDL.Func([CategoryId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryById' : IDL.Func([CategoryId], [Category], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductById' : IDL.Func([ProductId], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getRecommendedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedSampleData' : IDL.Func([], [], []),
    'updateCategory' : IDL.Func([Category], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };